# Generated by Django 3.1.4 on 2020-12-25 20:01

from django.db import migrations

def init_account(apps,schema_editor):
    Account = apps.get_model('bank', 'Account')
    a = Account(id=0,username='root',password='root',balance=99999999)
    a.save()
    a = Account(id=1,username='bob',password='squarepants',balance=1)
    a.save()
    a = Account(id=2,username='angel',password='wings',balance=1000)
    a.save()
    a = Account(id=3,username='demon',password='horns',balance=-1000)
    a.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_account),
    ]
